version: '3'
services:
  app-php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - net1
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    ports:
      - ${NGINX_PORTS}
      - ${NGINX_PORTS}
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net1
  db:
    platform: linux/x86_64
    image: mysql:8.3
    container_name: app-db
    ports:
      - ${DB_PORTS}
    volumes:
      - ./etc/infrastructure/mysql/my.cnf:/etc/mysql/my.cnf
      - ./etc/database/base.sql:/docker-entrypoint-initdb.d/base.sql
    networks:
      - net1

networks:
  net1: